apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: weaviate.packages.kadras.io
spec:
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp:
              intoNs: weaviate
          template:
          - helmTemplate:
              name: weaviate
              namespace: weaviate
              path: config/helm/upstream/weaviate
              valuesFrom:
              - path: config/helm/values.yml
          - ytt:
              ignoreUnknownComments: true
              paths:
              - '-'
              - config/carvel
          - kbld: {}
      export:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-weaviate
          useKbldImagesLock: true
        includePaths:
        - config
